# Generated by Django 5.1.4 on 2025-01-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_preferred_currency_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'United States Dollar'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('GBP', 'British Pound Sterling'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('RUB', 'Russian Ruble'), ('KRW', 'South Korean Won'), ('TRY', 'Turkish Lira'), ('MXN', 'Mexican Peso'), ('BRL', 'Brazilian Real'), ('ZAR', 'South African Rand')], default='TRY', max_length=3),
        ),
    ]
